path(tristram, alphacentauri, 34).
path(tristram, snowdin, 100).
path(tristram, tambi, 63).
path(tristram, faerun, 108).
path(tristram, norrath, 111).
path(tristram, straylight, 89).
path(tristram, arbre, 132).
path(alphacentauri, snowdin, 4).
path(alphacentauri, tambi, 79).
path(alphacentauri, faerun, 44).
path(alphacentauri, norrath, 147).
path(alphacentauri, straylight, 133).
path(alphacentauri, arbre, 74).
path(snowdin, tambi, 105).
path(snowdin, faerun, 95).
path(snowdin, norrath, 48).
path(snowdin, straylight, 88).
path(snowdin, arbre, 7).
path(tambi, faerun, 68).
path(tambi, norrath, 134).
path(tambi, straylight, 107).
path(tambi, arbre, 40).
path(faerun, norrath, 11).
path(faerun, straylight, 66).
path(faerun, arbre, 144).
path(norrath, straylight, 115).
path(norrath, arbre, 135).
path(straylight, arbre, 127).

path(alphacentauri, tristram, 34).
path(snowdin, tristram, 100).
path(tambi, tristram, 63).
path(faerun, tristram, 108).
path(norrath, tristram, 111).
path(straylight, tristram, 89).
path(arbre, tristram, 132).
path(snowdin, alphacentauri, 4).
path(tambi, alphacentauri, 79).
path(faerun, alphacentauri, 44).
path(norrath, alphacentauri, 147).
path(straylight, alphacentauri, 133).
path(arbre, alphacentauri, 74).
path(tambi, snowdin, 105).
path(faerun, snowdin, 95).
path(norrath, snowdin, 48).
path(straylight, snowdin, 88).
path(arbre, snowdin, 7).
path(faerun, tambi, 68).
path(norrath, tambi, 134).
path(straylight, tambi, 107).
path(arbre, tambi, 40).
path(norrath, faerun, 11).
path(straylight, faerun, 66).
path(arbre, faerun, 144).
path(straylight, norrath, 115).
path(arbre, norrath, 135).
path(arbre, straylight, 127).
